name: test2_mononav
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cuda=11.7.1
  - h5py=3.7.0
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - numpy=1.24.1
  - opencv=4.6.0
  - pip=22.3.1
  - python=3.9.7
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - scipy=1.10.0
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - ffmpeg=5.1.2
  - pip:
    - huggingface-hub==0.11.1
    - timm==0.6.12
    - tqdm==4.64.1
    - wandb==0.13.9
    - cflib==0.1.23 # crazyflie
    - cfclient==2023.6 # crazyflie
    - open3d==0.18.0 # mononav
    - Pillow==9.4.0 # mononav 
    - pynput==1.7.6 # mononav
    - PyYAML==5.4.1 # mononav
    - trimesh==3.22.1 # mononav

